# Generated by Django 6.1.1 on 2026-09-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Paste direct image URL", null=True
            ),
        ),
    ]
