# Generated by Django 6.1.1 on 2026-09-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image_url",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="book_covers/"),
        ),
    ]
